### ISSUE TITLE
直接打开Mapper.java文件无法找到对应的xml

### ISSUE THREAD

**Issue by hellozhongying** [niko-liu/vscode-mybatisx#1]
需要先打开对应的mapper.xml再跳转到对应的mapper.java文件，然后才显示Go To Xml

vsccode-mybatisx Version: 1.1.0

版本: 1.37.1 (user setup)
提交: f06011ac164ae4dc8e753a3fe7f9549844d15e35
日期: 2019-08-15T16:17:55.855Z
Electron: 4.2.7
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Windows_NT x64 10.0.17134

**Comment by niko-liu** [comment]
> 需要先打开对应的mapper.xml再跳转到对应的mapper.java文件，然后才显示Go To Xml
> 
> vsccode-mybatisx Version: 1.1.0
> 
> 版本: 1.37.1 (user setup)
> 提交: f06011ac164ae4dc8e753a3fe7f9549844d15e35
> 日期: 2019-08-15T16:17:55.855Z
> Electron: 4.2.7
> Chrome: 69.0.3497.128
> Node.js: 10.11.0
> V8: 6.9.427.31-electron.0
> OS: Windows_NT x64 10.0.17134

已经在跟进，下一个版本修复

**Comment by niko-liu** [comment]
> 需要先打开对应的mapper.xml再跳转到对应的mapper.java文件，然后才显示Go To Xml
> 
> vsccode-mybatisx Version: 1.1.0
> 
> 版本: 1.37.1 (user setup)
> 提交: f06011ac164ae4dc8e753a3fe7f9549844d15e35
> 日期: 2019-08-15T16:17:55.855Z
> Electron: 4.2.7
> Chrome: 69.0.3497.128
> Node.js: 10.11.0
> V8: 6.9.427.31-electron.0
> OS: Windows_NT x64 10.0.17134

1.2.0的新版本已发布

**Comment by hellozhongying** [comment]
@niko-liu 已更新，目前使用正常。
提个功能建议：目前mapper.java可以直接跳转到mapper.xml中具体的函数，但是从mapper.xml就只能通过namespace那里跳转到mapper.java文件，而不能跳转定位到具体的函数。所以是否可以在mapper.xml中增加通过sql的id跳转到对应的mapper.java中的函数？

**Comment by niko-liu** [comment]
> @niko-liu 已更新，目前使用正常。
> 提个功能建议：目前mapper.java可以直接跳转到mapper.xml中具体的函数，但是从mapper.xml就只能通过namespace那里跳转到mapper.java文件，而不能跳转定位到具体的函数。所以是否可以在mapper.xml中增加通过sql的id跳转到对应的mapper.java中的函数？

正准备加，下一版本加上去
